# A conda env for the pymt clinic
#
# Install with:
#
#    $ conda env create --file=environment.yml

name: live
channels:
  - conda-forge/label/dev
  - conda-forge
dependencies:
  - python
  - pymt
  - notebook
